name: flutter_pokedex
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  go_router: ^14.8.1
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  go_router_builder: ^2.8.2
  build_runner: ^2.4.15
  freezed: ^3.0.3
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - .env
