name: Flutter CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install FVM
        run: |
          dart pub global activate fvm

      - name: Setup Flutter with FVM
        run: |
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          fvm install
          fvm use
          echo "FVM configured with Flutter $(fvm flutter --version)"

      - name: Install dependencies
        run: fvm flutter pub get

      - name: Run Flutter linting
        run: fvm flutter analyze

      - name: Run tests with coverage
        run: fvm flutter test --coverage --test-randomize-ordering-seed random

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov.info
          fail_ci_if_error: true
          verbose: true
